import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ScrollArea } from "@/components/ui/scroll-area";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Supper App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-0 p-0 flex flex-col h-screen`}>
        <Nav />
        <ScrollArea className="flex-1 w-full border-t rounded-none overflow-y-auto">
          {children}
        </ScrollArea>
      </body>
    </html>
  );
}
