import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ScrollArea } from "@/components/ui/scroll-area"
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Supper App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <ScrollArea>
          <Nav />
          <main>
            {children}
          </main>
        </ScrollArea>
      </body>
    </html>
  );
}
